exports.bodyParser = require('body-parser')
exports.session = require('express-session')
exports.flash = require('express-flash')
exports.allowCrossDomain = require('./allow-cross-domain')
exports.isAdmin = require('./is-admin')