exports.bodyParser = require('body-parser')
exports.session = require('express-session')
exports.flash = require('express-flash')
exports.allowCrossDomain = require('./allowCrossDomain')
exports.isAdmin = require('./isAdmin')